# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'S3.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_S3(object):
    def setupUi(self, S3):
        S3.setObjectName("S3")
        S3.resize(1280, 960)
        S3.setMinimumSize(QtCore.QSize(1280, 960))
        S3.setMaximumSize(QtCore.QSize(1280, 960))
        self.centralwidget = QtWidgets.QWidget(S3)
        self.centralwidget.setObjectName("centralwidget")
        self.NEXTbutton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.NEXTbutton_2.setGeometry(QtCore.QRect(850, 880, 200, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.NEXTbutton_2.setFont(font)
        self.NEXTbutton_2.setObjectName("NEXTbutton_2")
        self.NEXTbutton = QtWidgets.QPushButton(self.centralwidget)
        self.NEXTbutton.setGeometry(QtCore.QRect(1070, 880, 200, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.NEXTbutton.setFont(font)
        self.NEXTbutton.setObjectName("NEXTbutton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(470, 20, 700, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(40, 250, 700, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 100, 700, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(40, 400, 700, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_3.setGeometry(QtCore.QRect(40, 570, 700, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setObjectName("radioButton_3")
        S3.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(S3)
        self.statusbar.setObjectName("statusbar")
        S3.setStatusBar(self.statusbar)

        self.retranslateUi(S3)
        QtCore.QMetaObject.connectSlotsByName(S3)

    def retranslateUi(self, S3):
        _translate = QtCore.QCoreApplication.translate
        S3.setWindowTitle(_translate("S3", "Optimal Samples selection System"))
        self.NEXTbutton_2.setText(_translate("S3", "Previous"))
        self.NEXTbutton.setText(_translate("S3", "NEXT"))
        self.label.setText(_translate("S3", "Optimal Samples selection System"))
        self.radioButton.setText(_translate("S3", "Define position and number"))
        self.label_2.setText(_translate("S3", "Pleas select the filter methods"))
        self.radioButton_2.setText(_translate("S3", "Define position and range of number"))
        self.radioButton_3.setText(_translate("S3", "Select a position as a fixed number"))
